#!/bin/sh
#
# Shell script to start the MongoDB Docker image.
#
# Copyright 2016-2019, Frederico Martins
#   Author: Frederico Martins <http://github.com/fscm>
#
# SPDX-License-Identifier: MIT
#
# This program is free software. You can use it and/or modify it under the
# terms of the MIT License.
#

set -e

BASENAME=$(basename "${0}")


# Variables
ACTION_HELP=0
ACTION_INIT=0
ACTION_START=0

__MONGODB_DATA__="/data/mongodb"


# Usage
function show_usage() {
  echo "Usage: ${BASENAME} [options] (help|init|start)"
  echo "  help:"
  echo "    <none>"
  echo "  init:"
  echo "    <none>"
  echo "  start:"
  echo "    <none>"
}


# Options parsing
while getopts "::" opt; do
  case ${opt} in
    \?)
      echo >&2 "  [ERROR] Invalid option: -${OPTARG}"
      exit 1
      ;;
    :)
      echo >&2 "  [ERROR] Option -${OPTARG} requires an argument"
      exit 2
      ;;
  esac
done

shift $((OPTIND-1))

for command in "${@}"; do
  case "${command}" in
    [Hh][Ee][Ll][Pp])
      ACTION_HELP=1
      ;;
    [Ii][Nn][Ii][Tt])
      ACTION_INIT=1
      ;;
    [Ss][Tt][Aa][Rr][Tt])
      ACTION_START=1
      ;;
    *)
      echo >&2 "  [WARN] Unknown command '${command}'"
      ;;
  esac
done


# Check arguments
if [ $# -eq 0 ]; then
  show_usage
  exit 3
fi
if [ "$((ACTION_HELP+ACTION_INIT+ACTION_START))" -eq 0 ]; then
  show_usage
  exit 0
fi


# Check permissions
#if [[ "$(id -u)" -ne 0 ]]; then
#  echo >&2 "  [ERROR] This script requires privileged access to system files"
#  exit 4
#fi


# === HELP ===
if [ "${ACTION_HELP}" -gt 0 ]; then
  show_usage
  exit 0
fi


# === INIT ===
if [ "${ACTION_INIT}" -gt 0 ]; then

  # Nothing to do
  echo "  [INFO] NOTHING TO DO. run the 'start' command."

  # All done
  echo "  [INFO] Configuration(s) successfully updated"
fi


# === START ===
if [ "${ACTION_START}" -gt 0 ]; then

  # Create temporary dir (if needed)
  if ! [[ -d /tmp ]]; then
    mkdir -m 1777 /tmp
  fi

  # Create data dir (if needed)
  if ! [ -d ${__MONGODB_DATA__} ]; then
    mkdir -m 0755 ${__MONGODB_DATA__}
  fi

  # Start the MongoDB server
  /bin/mongod --bind_ip_all --dbpath ${__MONGODB_DATA__}
fi

# All done
exit 0
